# Generated by Django 5.0.4 on 2024-04-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cashback', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashbackoffer',
            name='limitations',
        ),
        migrations.AddField(
            model_name='cashbackoffer',
            name='company',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='criteria',
            name='days_of_week',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cashbackoffer',
            name='valid_from',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('APPLE_PAY', 'Apple Pay'), ('GOOGLE_PAY', 'Google Pay'), ('SAMSUNG_PAY', 'Samsung Pay')], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Limitations',
        ),
    ]
