# Generated by Django 5.0.4 on 2024-04-13 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cashback', '0002_remove_cashbackoffer_limitations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteria',
            name='bank_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
